replicaCount: 3

service:
  type: LoadBalancer
  port: 8080

ingress:
  host: prod.py-bookstore-api.cloud

env:
  DATABASE_URL: "sqlite:///./books.db"
  LOG_LEVEL: "INFO"
  PAGE_SIZE: 10
  APP_ENV: "prod"
  HOST: "0.0.0.0"
  PORT: 8080
  RELOAD: "False"
  ALLOWED_ORIGINS: "*"
  DB_POOL_SIZE: 5
  DB_MAX_OVERFLOW: 10