replicaCount: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  host: dev.py-bookstore-api.cloud

env:
  DATABASE_URL: "sqlite:///./books.db"
  LOG_LEVEL: "INFO"
  PAGE_SIZE: 10
  APP_ENV: "dev"
  HOST: "0.0.0.0"
  PORT: 8080
  RELOAD: "True"
  ALLOWED_ORIGINS: "*"
  DB_POOL_SIZE: 5
  DB_MAX_OVERFLOW: 10