name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: 'Image tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "Deploying from branch ${GITHUB_REF#refs/heads/}"
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Create kubeconfig file
        env:
          KUBECONFIG_CONTENT: ${{ secrets.KUBE_CONFIG_DEV }}
        run: |
          echo "$KUBECONFIG_CONTENT" > kubeconfig
          export KUBECONFIG=kubeconfig
      - name: Run Helm upgrade
        env:
          KUBECONFIG: kubeconfig
        run: |
          helm upgrade --install py-bookstore-api ./py-bookstore-api-chart -f ./py-bookstore-api-chart/values-staging.yaml --set image.repository=${{ secrets.DOCKER_USERNAME }}/py_bookstore-api --set image.tag=${{ github.event.inputs.IMAGE_TAG }}